### ISSUE TITLE
Does not work with houdini 20.5

### ISSUE THREAD

**Issue by Liametc** [Aeoll/ae_SVG#12]
`Traceback (most recent call last):
  File "ae::Sop/SVG_Import::2, PythonModule", line 10, in <module>
  File "/media/software/sidefx/hfs20.5.278-py310/houdini/python3.10libs/toolutils.py", line 1886, in createModuleFromSection
    return _createModule(module_name,
  File "/media/software/sidefx/hfs20.5.278-py310/houdini/python3.10libs/toolutils.py", line 1868, in _createModule
    eval(code, module_dict)
  File "path", line 3, in <module>
ImportError: cannot import name 'MutableSequence' from 'collections' (/media/software/sidefx/hfs20.5.278-py310/python/lib/python3.10/collections/__init__.py)`

Need to update for python 3.10

**Comment by takavfx** [comment]
@Liametc 
Hi.
I fixed this for Houdini 20.5 with Python 3.11 & Python 3.10.
I'm trying to PR from the fork I did, but I'm not sure @Aeoll is still in active now. So please try that fork instead.
https://github.com/takavfx/ae_SVG/tree/feature/takvfx/add_support_for_houdini_20.5

![image](https://github.com/user-attachments/assets/f0c0e82d-81b5-41b0-b581-70430e104efb)
